### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by mrx23dot** [project-mk-ultra/torrent-tracker-scraper#30]
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> from torrent_tracker_scraper import scraper
>>> scr = scraper.Scraper(infohashes=['8F1F23263E454A6B12B271BB13FF010522BD3D1F'])
>>> res = scr.scrape()
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python36\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Python36\lib\site-packages\torrent_tracker_scraper\scraper.py", line 143, in scrape_tracker
    res = self.connection.sock.recv(8 + (12 * len(self.infohashes)))
OSError: [WinError 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to rec
eive a datagram into was smaller than the datagram itself
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\torrent_tracker_scraper\scraper.py", line 186, in scrape
    results = list(filter(lambda result: result != [], results.get()))
  File "C:\Python36\lib\multiprocessing\pool.py", line 670, in get
    raise self._value
OSError: [WinError 10040] A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to rec
eive a datagram into was smaller than the datagram itself
>>>

**Comment by zawi99** [comment]
Thanks for creating an issue. We'll have a look at that and fix asap.

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
@mrx23dot thank you for reporting the issue. We are investigating and we'll fix it soon

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
Related to #31
