### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by 49e94b8f256530dc0d41f740dfe8a4c1** [project-mk-ultra/torrent-tracker-scraper#34]

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
New features sometimes cause breaking changes. 

A changelog would document this. 

Using this https://pypi.org/project/gitchangelog/ would be a nice start

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
I guess we have to wipe the repo history and make useful commit messages henceforth.

**Comment by zawi99** [comment]
We can also leave history as it is and just start using [gitchangelog](https://github.com/vaab/gitchangelog) and use [partial changelog generation](https://github.com/vaab/gitchangelog#incremental-changelog).

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
> We can also leave history as it is and just start using [gitchangelog](https://github.com/vaab/gitchangelog) and use [partial changelog generation](https://github.com/vaab/gitchangelog#incremental-changelog).

I already considered this. 

However, the commits don't have tags. I also looked into filtering using regex patterns but the commits vary so wildly. I tried working out a solution with `git rebase` but what's the point, the early stages of the project didn't even use feature branches (my bad :( )

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
With respect to the comment above, I propose to wipe the history but properly document every feature the module offers
