### ISSUE TITLE
Options should use kwargs

### ISSUE THREAD

**Issue by 49e94b8f256530dc0d41f740dfe8a4c1** [project-mk-ultra/torrent-tracker-scraper#35]

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
https://github.com/project-mk-ultra/torrent-tracker-scraper/issues/25#issuecomment-679956959

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
https://book.pythontips.com/en/latest/args_and_kwargs.html

**Comment by zawi99** [comment]
> [#25 (comment)](https://github.com/project-mk-ultra/torrent-tracker-scraper/issues/25#issuecomment-679956959)

I was wrong... And I lied... All parameters are still optional. Sorry for confusion.

I'll close the ticket.
