### ISSUE TITLE
Standardise error message for easier iteration

### ISSUE THREAD

**Issue by 49e94b8f256530dc0d41f740dfe8a4c1** [project-mk-ultra/torrent-tracker-scraper#47]
Replace

`['Socket timeout for tracker.fileparadise.in:1337: timed out']`

with 

`{'tracker': 'udp://tracker.fileparadise.in:1337', 'results': [], 'error': 'Socket timeout for tracker.fileparadise.in:1337: timed out }`

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
Fixed in #46

**Comment by zawi99** [comment]
I think that it might be a breaking change for users whose handle invalid results. What do you think? We might mention that in the changelog  https://github.com/project-mk-ultra/torrent-tracker-scraper/issues/34

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
Yeah we really need that changelog. I'll give it a higher priority
